version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: levelup-postgres
    restart: always
    environment:
      POSTGRES_USER: rokki
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: goaltracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
